// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFBTXsdO9h7aJ7BH5oa0IxRkhP2tkRk80',
    appId: '1:982610407227:web:86160ce19bef4f71cc111e',
    messagingSenderId: '982610407227',
    projectId: 'managerapp-c5141',
    authDomain: 'managerapp-c5141.firebaseapp.com',
    storageBucket: 'managerapp-c5141.firebasestorage.app',
    measurementId: 'G-5KJM5C5F5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9b11ZMvTEW27HZmR79ka6MuCHR7O01k',
    appId: '1:982610407227:android:1c756ba6dc6c98aacc111e',
    messagingSenderId: '982610407227',
    projectId: 'managerapp-c5141',
    storageBucket: 'managerapp-c5141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0OkmNhK_Q7enaWDHNtxZhpbc63VOYt6M',
    appId: '1:982610407227:ios:b12e68604800bd14cc111e',
    messagingSenderId: '982610407227',
    projectId: 'managerapp-c5141',
    storageBucket: 'managerapp-c5141.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0OkmNhK_Q7enaWDHNtxZhpbc63VOYt6M',
    appId: '1:982610407227:ios:b12e68604800bd14cc111e',
    messagingSenderId: '982610407227',
    projectId: 'managerapp-c5141',
    storageBucket: 'managerapp-c5141.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFBTXsdO9h7aJ7BH5oa0IxRkhP2tkRk80',
    appId: '1:982610407227:web:7f8dc46205212892cc111e',
    messagingSenderId: '982610407227',
    projectId: 'managerapp-c5141',
    authDomain: 'managerapp-c5141.firebaseapp.com',
    storageBucket: 'managerapp-c5141.firebasestorage.app',
    measurementId: 'G-0W6RL5N7Y5',
  );
}